# Generated by Django 2.2.15 on 2020-08-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0110_auto_20200816_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='caseformat',
            field=models.CharField(blank=True, choices=[('standard', 'Estàndard/fixe'), ('stop', 'STOP al final'), ('multicas', 'Linies per cada cas'), ('indiv', 'Casos individuals')], max_length=10, verbose_name='case format'),
        ),
    ]
