# Generated by Django 2.2.15 on 2020-08-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0112_auto_20200824_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='output_prefix',
            field=models.IntegerField(blank=True, null=True, verbose_name='dddddddddddddddddddddddddd prefix length'),
        ),
    ]
