# Generated by Django 2.2.15 on 2020-08-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0113_auto_20200824_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='caseformat',
            field=models.CharField(choices=[('standard', 'Estàndard/fixe'), ('stop', 'STOP al final'), ('multicas', 'Linies per cada cas'), ('indiv', 'Casos individuals')], default='standard', max_length=10, verbose_name='case format'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('sorted', 'ffffffffffffffffffffffffffffffffffffffffff'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line')], max_length=10, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='output_prefix',
            field=models.IntegerField(blank=True, null=True, verbose_name='prefix length'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('sorted', 'ffffffffffffffffffffffffffffffffffffffffff'), ('identical', 'Byte identical'), ('linecount', 'Line-by-line')], max_length=10, verbose_name='checker'),
        ),
    ]
