# Generated by Django 2.2.15 on 2020-08-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0115_auto_20200826_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('rstripped', 'Compara contra fitxer'), ('sorted', 'Linea a Linea (només profes)'), ('identical', 'Programame-like'), ('linecount', 'Line-by-line')], max_length=10, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('rstripped', 'Compara contra fitxer'), ('sorted', 'Linea a Linea (només profes)'), ('identical', 'Programame-like'), ('linecount', 'Line-by-line')], max_length=10, verbose_name='checker'),
        ),
    ]
